upstream perseus-core {
    server 127.0.0.1:8000;
}

upstream perseus-frontend {
    server 127.0.0.1:8001;
}

server {
    listen       80 default_server;
    listen  [::]:80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

# in case you have alternative domains you want to reach PERSEUS at, use the following (otherwise drop it)
server {
    listen       443 ssl;
    listen  [::]:443 ssl;
    server_name <ALT_HOST_1> <ALT_HOST_2> ...; # i.e. perseus.pc2.upb.de www.perseus.pc2.upb.de ...

    # change the path to your SSL certificate
    ssl_certificate     /path/to/ssl_certificate.pem;
    ssl_certificate_key /path/to/ssl_certificate_key.pem;

    return 301 <HOST>$request_uri; # i.e. https://perseus.pc2.uni-paderborn.de$request_uri
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;
    server_name <HOST_1> <HOST_2> ...; # i.e. perseus.pc2.uni-paderborn.de www.perseus.pc2.uni-paderborn.de ...

    # change the path to your SSL certificate
    ssl_certificate     /path/to/ssl_certificate.pem;
    ssl_certificate_key /path/to/ssl_certificate_key.pem;

    client_max_body_size 25M;

    location / {
        proxy_pass http://perseus-frontend;
    }

    location /api/ {
        rewrite ^/api(/.*)$ $1 break;
        proxy_pass http://perseus-core;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_buffering off;
    }
}
